#!/bin/bash
set -euo pipefail

export CONDA_ENV_NAME=${CONDA_ENV_NAME:-llama2_vllm}
export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0,3,4,5}
export MODEL_PATH=${MODEL_PATH:-/zhdd/home/tjshen/models/Qwen2.5-1.5B-Instruct}
export REWARD_MODEL_PATH=${REWARD_MODEL_PATH:-/zhdd/home/tjshen/260413_Backup_model_resume_20260323_031320/Skywork-Reward-Llama-3.1-8B-v0.2}

export PROJECT_NAME=${PROJECT_NAME:-ArcherCodeR-V14-Qwen25-1_5B-5090Hao}
export EXP_NAME=${EXP_NAME:-train_v14_5090hao_qwen25_1_5b_4gpu_bsz32}
export OUTPUT_ROOT=${OUTPUT_ROOT:-./output_5090_Hao}
export DYNAMIC_METHOD=${DYNAMIC_METHOD:-sample_taylor_v13}
export TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS:-50}
export SAVE_FREQ=${SAVE_FREQ:-50}
export SAVE_STEPS=${SAVE_STEPS:-10,50}

export TRAIN_PROMPT_BSZ=${TRAIN_PROMPT_BSZ:-32}
export TRAIN_PROMPT_MINI_BSZ=${TRAIN_PROMPT_MINI_BSZ:-8}
export ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.45}

export SHADOW_ANCHOR_SIZE_PER_DOMAIN=${SHADOW_ANCHOR_SIZE_PER_DOMAIN:-128}
export CANDIDATE_MULTIPLIER=${CANDIDATE_MULTIPLIER:-4}
export GRAD_PROJECTION_DIM=${GRAD_PROJECTION_DIM:-256}
export CURVATURE_REFRESH_FREQ=${CURVATURE_REFRESH_FREQ:-50}

export DISABLE_PYTORCH_CUDA_ALLOC_CONF=${DISABLE_PYTORCH_CUDA_ALLOC_CONF:-1}
export RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES=${RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES:-1}
export ARCHER_HIDE_FLASH_ATTN_FROM_VLLM=${ARCHER_HIDE_FLASH_ATTN_FROM_VLLM:-1}
export VLLM_ATTENTION_BACKEND=${VLLM_ATTENTION_BACKEND:-FLASHINFER}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec "${SCRIPT_DIR}/dynamic_train_v13_a100_formal.sh"
